# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1329c65ada918b5a9b85a3066d03ed3c280a9917ee8c7dc5006f993f809b9784db5832b6e9b3c52fb9e005549ca8245ed4f575c3b223748e00f1745ed64b74c

test:
  secret_key_base: 0f8d0cf97bfe97d70772cf612cb56ad1909906df05850b458fcec638262dfc31d3df39f14438b1af916ea5bc84718ff585ba396bbb0c0abf75f31556a5861150

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
